name: Deploy Front to Firebase Hosting
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1 — Checkout
      - uses: actions/checkout@v4

      # 2 — Node / pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install & build
        run: |
          cd web
          pnpm i --frozen-lockfile
          pnpm run build      # creates web/dist

      # 3 — Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ai-act-copilot-fe      # change if you named it differently
          channelId: live                   # "live" = production
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # set this secret in your repo settings
